### ISSUE TITLE
funny 😆 

### ISSUE THREAD

**Issue by floydkim** [WayneKim92/react-native-thaumatrope#1]
give me some photo of NB 😠 🔪

**Comment by Wayne-Kim** [comment]
![image](https://github.com/user-attachments/assets/df8ec6d1-736a-46c2-bc47-6e3047c64ae9)

**Comment by floydkim** [comment]
wow i'm happy 😄 
thank you

**Comment by Wayne-Kim** [comment]
<img width="485" alt="image" src="https://github.com/user-attachments/assets/ce042a89-ed27-40b3-8079-c851fdb6025d">

**Comment by floydkim** [comment]
😍

**Comment by Wayne-Kim** [comment]
This is 2024 Limited Edition Christmas NB Emoji.

Rudolph NB, who didn't receive a gift but only a present.

![image](https://github.com/user-attachments/assets/9089b058-7c7d-448c-9f59-ae1683877537)

![image](https://github.com/user-attachments/assets/7a275cc0-b1f2-4b94-8607-d8b6c3331928)

**Comment by floydkim** [comment]
cute 😍 
<img src="https://github.com/user-attachments/assets/5afaaf12-723b-472c-89b1-c46080b5bd39" width=100 />
<img src="https://github.com/user-attachments/assets/11dcac84-4f64-400c-821f-6c4eac421502" width=100 />
